
# Group Service

## /api/v1/kolide/forgot_password

### Forgot Password [POST]
Sends a password reset email.

+ Request 
    + Body

            {"email":"nobody@kolide.co"}        

+ Response 404 (application/json; charset=utf-8)



    + Body

            {
                "error": "resource not found"
            }
        



## /api/v1/kolide/hosts

### List Hosts [GET]
List hosts

+ Request 

    + Headers
            
            Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzZXNzaW9uX2tleSI6Inh0dkIvMDJnMlc0VzRDbWtwNzNydmdvalc4NFQ2SDBDdHFZOXVscVRmT3BzUVZSSjZUdjNtZXpZOW9Vam1aQnhnUmlwTEpNQzk0VUJJV1ZYT3V6UXdRPT0ifQ.n04S_nQly4RBxUhRrlWLFFh7WzcI-d4sFuVv20TDu9g

+ Response 200 (application/json; charset=utf-8)



    + Body

            {
                "hosts": []
            }
        



## /api/v1/kolide/hosts/1

### Delete Host [DELETE]
Delete a host by ID

+ Request 

    + Headers
            
            Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzZXNzaW9uX2tleSI6IkdzVHFTMDR5WnJnbE1Wd1dDWG1rUmxmcnM4TU1kUlJjdi9zTXBCTXZnN1J3TWUyK3FSZGpRK0JyZk1IUVRIeitLWXdodUNRU0hvaHp3bUU1WXQrdWZnPT0ifQ.jLPfepgz7Y6fAdKTSpEin6KGO6HXEhmsd4QX7PvQ6BI

+ Response 404 (application/json; charset=utf-8)



    + Body

            {
                "error": "resource not found"
            }
        


### Get Host [GET]
Get a host by ID

+ Request 

    + Headers
            
            Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzZXNzaW9uX2tleSI6ImJUQnJWTUQ0UjNWRFJ2Yk05MjNwSU00OWVSNm4xVE1ibmxqc0wxWlpQbUdzQVFaS2tqam1KaWFvNVBhYlFWUGNvZjZsc0NON2hPb0VReFVsTmVpaVN3PT0ifQ.1Sg2cYG0_nQOciSGh6SgvOkWUy0oipB5IZnJQpGdsEg

+ Response 404 (application/json; charset=utf-8)



    + Body

            {
                "error": "resource not found"
            }
        



## /api/v1/kolide/invites

### List Invites [GET]
List invited users

+ Request 

    + Headers
            
            Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzZXNzaW9uX2tleSI6IlRKOWxDUUp4SDh2NDJCSXNOQy9zbUYreXl0UUxiZW5DdUVkL3dSZFliRXZVd3dTSk9FOEVzR0hMK21wVGE4UWtCNnowbUJMV0Y2RGI2MUpQYXN3bGdBPT0ifQ.IfkClmu3jIyt9_AGm-ubiEi7_E8pCa6FoZEhD2aPTew

+ Response 200 (application/json; charset=utf-8)



    + Body

            {
                "invites": []
            }
        



## /api/v1/kolide/invites/1

### Delete Invite [DELETE]
Delete invite by ID.

+ Request 

    + Headers
            
            Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzZXNzaW9uX2tleSI6Ildpc29HZDFCdkRCVTE2b1ZXb0VGeGdyNGduTGdtM0kvYXFqU0NwZHphbGJES0t1Qlc0Z3lMSW9Sd1VjSTN2aEVkVm4xSHg0NXRKNnhucVJCUjExV0N3PT0ifQ.SAdP6F6-Xy_ceoEQKMpHtPc5No3hmhsn5qjmZg2HMKs

+ Response 200 (application/json; charset=utf-8)



    + Body

            {
                "error": {}
            }
        



## /api/v1/kolide/login

### Login [POST]
Logs a user in.

+ Request 
    + Body

            {
                        "username": "admin1",
                        "password": "foobar"
                        }        

+ Response 200 (application/json; charset=utf-8)



    + Body

            {
                "user": {
                    "id": 1,
                    "username": "admin1",
                    "name": "",
                    "email": "admin1@example.com",
                    "admin": true,
                    "enabled": true,
                    "force_password_reset": false,
                    "gravatar_url": ""
                },
                "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzZXNzaW9uX2tleSI6ImFRcnRtbXFicXh1ZUdjVFlEOGRtUU1PZ3NFb1lVRFZDdGhZbWtEaHpoeGF4UFhXd1NOTHFqQkQ1cmF3M2c0T2RXZS8xemlHV1ZPYVllQmJKUzc2TlZBPT0ifQ.4b28eujgbGMzHKKFwXm0MVx4UxXCBl-J2klshP5yEAE"
            }
        



+ Request 
    + Body

            {
                        "username": "nobody",
                        "password": "foobar"
                        }        

+ Response 401 (application/json; charset=utf-8)



    + Body

            {
                "message": "Authentication Failed",
                "error": "username or email and password do not match"
            }
        



## /api/v1/kolide/logout

### Logout [POST]
Logs a user out.

+ Request 

    + Headers
            
            Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzZXNzaW9uX2tleSI6ImRQeTd1YklCT1JGek13UDUxYm1IelVHT0F4TGhxWDRweUMvSExzY25RRU9vRnlNaFV3cGZqbjg2R2tyZklZWkRPNkZFQjBpQVdSbEx2clEzSm9FcW1nPT0ifQ.Jc-YxXbh71AnuLCiTi4Uif8k-T05I7Gby-j8PX1G01Y

+ Response 200 (application/json; charset=utf-8)



    + Body

            {}
        



## /api/v1/kolide/me

### Current Session User [GET]
Returns info about the currently logged in user

+ Request 

    + Headers
            
            Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzZXNzaW9uX2tleSI6Im1qS09aa1VlL00xUkFGMi9YRktiZmhBcGo0NDEwU2I1d3JSWElJTldnVkJyYWpzeUQ2dkVTK0s3Q3M4L1pyQW1KT3VGTXFmYWNqUkJ5UTVFaDhudzZBPT0ifQ.91HwSkafyyVUCso6SjoRcmV4cDjOTWL8oZbDk4iaErk

+ Response 200 (application/json; charset=utf-8)



    + Body

            {
                "user": {
                    "id": 1,
                    "username": "admin1",
                    "name": "",
                    "email": "admin1@example.com",
                    "admin": true,
                    "enabled": true,
                    "force_password_reset": false,
                    "gravatar_url": ""
                }
            }
        



## /api/v1/kolide/sessions/1

### Delete Session [DELETE]
Delete session by ID

+ Request 

    + Headers
            
            Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzZXNzaW9uX2tleSI6Ik5MNlRxMmZocTQ3d0cwR2dIQXdQZjgyTkN3bUZ6OXVMV2loRjRXZVZWVDhPa1VoRy8xUHdNeUtzYzV4bk1PS2QxZ0Ewa3ZEUHpRRGdwd2JCZFdaSXlRPT0ifQ.uIULwc70EVQyx8Ev0Jv5lfNZpAmPHNEo6gkGsQ4aX2Q

+ Response 404 (application/json; charset=utf-8)



    + Body

            {
                "error": "resource not found"
            }
        


### Get Session Info [GET]
Return session info

+ Request 

    + Headers
            
            Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzZXNzaW9uX2tleSI6IjBrTlZodkdQS29xU1QraHFLSVhBMUNnU2JaQmF6NE93NW1YWUJvUTdqeVhzM1FxbFRqWXV0d2FzWE5qV2ZRbmlHYkIwbnJuRnFWR2QvWDZ4SDJJS1FRPT0ifQ.nHm4ULA4qvIGTYPvJ4-DAnPlOm-MaD1L87cVXfmSMTk

+ Response 404 (application/json; charset=utf-8)



    + Body

            {
                "error": "resource not found"
            }
        



## /api/v1/kolide/users

### List Users [GET]
Return a list of users

+ Request 

    + Headers
            
            Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzZXNzaW9uX2tleSI6IjBHMGZhRXlZT1VSWDFmZ05sZDlDa3kxWnVESjd1TkE5a1JsY2hKK1UySHhEUkplNmlWMjJmVWFEMGdDT0dZUTBmMTU1c0VHdXllenE5bVFBRWdFcmlBPT0ifQ.SYrIxjaPei3zTwrMXICN6z9o1_bqDCh-x3KlRzE7C7I

+ Response 200 (application/json; charset=utf-8)



    + Body

            {
                "users": [
                    {
                        "id": 1,
                        "username": "admin1",
                        "name": "",
                        "email": "admin1@example.com",
                        "admin": true,
                        "enabled": true,
                        "force_password_reset": false,
                        "gravatar_url": ""
                    },
                    {
                        "id": 2,
                        "username": "user1",
                        "name": "",
                        "email": "user1@example.com",
                        "admin": false,
                        "enabled": true,
                        "force_password_reset": false,
                        "gravatar_url": ""
                    },
                    {
                        "id": 3,
                        "username": "user2",
                        "name": "",
                        "email": "user2@example.com",
                        "admin": false,
                        "enabled": true,
                        "force_password_reset": false,
                        "gravatar_url": ""
                    },
                    {
                        "id": 4,
                        "username": "disabled1",
                        "name": "",
                        "email": "disabled1@example.com",
                        "admin": false,
                        "enabled": false,
                        "force_password_reset": false,
                        "gravatar_url": ""
                    }
                ]
            }
        



## /api/v1/kolide/users/1

### Get User [GET]
Return a single user by ID

+ Request 

    + Headers
            
            Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzZXNzaW9uX2tleSI6InZZNWxuNVp0THVESFl4dWxWTW9xM1BDc1FBNXBTbWdKRWEwWExXV1l1eUMxT1RCdlFiRVUxM1U3L2VoQ1Z0Zk1xSUw4bVYvZkVheTFSRU9OeEo0b2VRPT0ifQ.YTRGax9Q1DX90X8le6DKYEfFkBzOxd10sDkvfYlf8qo

+ Response 200 (application/json; charset=utf-8)



    + Body

            {
                "user": {
                    "id": 1,
                    "username": "admin1",
                    "name": "",
                    "email": "admin1@example.com",
                    "admin": true,
                    "enabled": true,
                    "force_password_reset": false,
                    "gravatar_url": ""
                }
            }
        


