// Automatically generated by mockimpl. DO NOT EDIT!

package mock

import "github.com/kolide/kolide/server/kolide"

var _ kolide.YARAStore = (*YARAStore)(nil)

type NewYARASignatureGroupFunc func(ysg *kolide.YARASignatureGroup) (*kolide.YARASignatureGroup, error)

type NewYARAFilePathFunc func(fileSectionName string, sigGroupName string) error

type YARASectionFunc func() (*kolide.YARASection, error)

type YARAStore struct {
	NewYARASignatureGroupFunc        NewYARASignatureGroupFunc
	NewYARASignatureGroupFuncInvoked bool

	NewYARAFilePathFunc        NewYARAFilePathFunc
	NewYARAFilePathFuncInvoked bool

	YARASectionFunc        YARASectionFunc
	YARASectionFuncInvoked bool
}

func (s *YARAStore) NewYARASignatureGroup(ysg *kolide.YARASignatureGroup) (*kolide.YARASignatureGroup, error) {
	s.NewYARASignatureGroupFuncInvoked = true
	return s.NewYARASignatureGroupFunc(ysg)
}

func (s *YARAStore) NewYARAFilePath(fileSectionName string, sigGroupName string) error {
	s.NewYARAFilePathFuncInvoked = true
	return s.NewYARAFilePathFunc(fileSectionName, sigGroupName)
}

func (s *YARAStore) YARASection() (*kolide.YARASection, error) {
	s.YARASectionFuncInvoked = true
	return s.YARASectionFunc()
}
