// Automatically generated by mockimpl. DO NOT EDIT!

package mock

import "github.com/kolide/kolide-ose/server/kolide"

var _ kolide.EmailChangesStore = (*EmailChangesStore)(nil)

type PendingEmailChangeFunc func(uid uint, newEmail string, token string) error

type CommitEmailChangeFunc func(token string) (string, error)

type EmailChangesStore struct {
	PendingEmailChangeFunc        PendingEmailChangeFunc
	PendingEmailChangeFuncInvoked bool

	CommitEmailChangeFunc        CommitEmailChangeFunc
	CommitEmailChangeFuncInvoked bool
}

func (s *EmailChangesStore) PendingEmailChange(uid uint, newEmail string, token string) error {
	s.PendingEmailChangeFuncInvoked = true
	return s.PendingEmailChangeFunc(uid, newEmail, token)
}

func (s *EmailChangesStore) CommitEmailChange(token string) (string, error) {
	s.CommitEmailChangeFuncInvoked = true
	return s.CommitEmailChangeFunc(token)
}
