// Automatically generated by mockimpl. DO NOT EDIT!

package mock

import "github.com/kolide/kolide-ose/server/kolide"

var _ kolide.LicenseStore = (*LicenseStore)(nil)

type SaveLicenseFunc func(jwt string) error

type LicenseFunc func() (*kolide.License, error)

type LicenseStore struct {
	SaveLicenseFunc        SaveLicenseFunc
	SaveLicenseFuncInvoked bool

	LicenseFunc        LicenseFunc
	LicenseFuncInvoked bool
}

func (s *LicenseStore) SaveLicense(jwt string) error {
	s.SaveLicenseFuncInvoked = true
	return s.SaveLicenseFunc(jwt)
}

func (s *LicenseStore) License() (*kolide.License, error) {
	s.LicenseFuncInvoked = true
	return s.LicenseFunc()
}
