// Automatically generated by mockimpl. DO NOT EDIT!

package mock

import (
	"encoding/json"

	"github.com/kolide/fleet/server/kolide"
)

var _ kolide.OsqueryOptionsStore = (*OsqueryOptionsStore)(nil)

type ApplyOptionsFunc func(options *kolide.OptionsSpec) error

type GetOptionsFunc func() (*kolide.OptionsSpec, error)

type OptionsForHostFunc func(host *kolide.Host) (json.RawMessage, error)

type OsqueryOptionsStore struct {
	ApplyOptionsFunc        ApplyOptionsFunc
	ApplyOptionsFuncInvoked bool

	GetOptionsFunc        GetOptionsFunc
	GetOptionsFuncInvoked bool

	OptionsForHostFunc        OptionsForHostFunc
	OptionsForHostFuncInvoked bool
}

func (s *OsqueryOptionsStore) ApplyOptions(options *kolide.OptionsSpec) error {
	s.ApplyOptionsFuncInvoked = true
	return s.ApplyOptionsFunc(options)
}

func (s *OsqueryOptionsStore) GetOptions() (*kolide.OptionsSpec, error) {
	s.GetOptionsFuncInvoked = true
	return s.GetOptionsFunc()
}

func (s *OsqueryOptionsStore) OptionsForHost(host *kolide.Host) (json.RawMessage, error) {
	s.OptionsForHostFuncInvoked = true
	return s.OptionsForHostFunc(host)
}
